### ISSUE TITLE
Propel is returning an unexpected number of rows

### ISSUE THREAD

**Issue by sinjuice** [propelorm/Propel2#1231] opened 2016-06-30 09:29 UTC
I'm trying to execute a query using propel and it should return 50 rows of data, but instead of that it returns other random number of rows. I printed the query copied in my pgphpadmin and it returns the 50 rows. I'm not sure what is happening. Also if I execute "count" function before "find" it returns 50, but after it returns the random amount of rows.

```
$limit = 50;
$offset = 0;
..... //filters 
$companies = $companies->orderById()->limit($limit)->offset($offset);
var_dump($companies->count()); // this returns 50
$companies = $companies->find();
var_dump($companies->count()); // this returns 13
```

Also the foreach after iterates only 13 times.

And this is the query generated

```
SELECT "company"."id", "company"."otherfields",
"lists"."id", "lists"."otherfields", "place"."id",
"place"."otherfields", "contact"."id", "contact"."otherfields", 
"entry"."id","entry"."otherfields" 
FROM "company" LEFT JOIN "lists" ON 
("company"."sector_id"="lists"."id") LEFT JOIN "place" ON 
("company"."country_id"="place"."id") LEFT JOIN "contact" ON  
("company"."id"="contact"."company_id" AND "contact"."active" = true)
LEFT JOIN "entry" ON ("company"."id"="entry"."company_id") 
WHERE "company"."active"=true ORDER BY "company"."id" ASC LIMIT 50 OFFSET 0
```

The Propel version is 2.0-dev

I always had a problem with this query so I think that the problem may come from the fact that I removed one **throw** in the library. I'm using with() and limit().  The query generated is ok, but the result is not. 

Changed Propel/Runtime/Formatter/ObjectFormatter.php
I've commented this.
```
            /*if ($this->hasLimit) {
                throw new LogicException('Cannot use limit() in conjunction with with() on a one-to-many relationship. Please remove the with() call, or the limit() call.');
            }*/
```

I imagine that the error might come from here. 

My join query looks like this

```
$companies->leftJoinWithLists()->leftJoinWithPlace()->leftJoinWithContact()->addJoinCondition('Contact','Contact.active = ?', true)->leftJoinWithEntry();
```
And then I add the limit. Any way to avoid this or do it other way?

[schema.txt](https://github.com/propelorm/Propel2/files/341122/schema.txt)

**Comment by staabm** [comment] 2016-06-30 09:47
we either need to close this issue, or the other duplicate https://github.com/propelorm/Propel/issues/1027#issuecomment-229601829

**Comment by staabm** [comment] 2016-06-30 09:48
closed the other issue, because it seems you are using propel2.

**Comment by sinjuice** [comment] 2016-06-30 09:49
Yes, sorry for the duplicate.

I think that the problem is that the relation with Contact can return more than one result. Any way to filter and limit it to 1?(After the join I might filter by Contact)

**Comment by benbankes** [comment] 2016-06-30 11:16
Let's be clear.  This is not a bug.  The `LogicException` that @sinjuice conveniently comments out exists for a reason.  While the SQL `LIMIT` clause limits the number of rows returned by SQL, the information from multiple rows in the LEFT JOIN result may come from only one row of the left table in the join (in this case, company).  It looks like this is a non-issue.  @sinjuice You can either use two queries or try a subquery.

**Comment by sinjuice** [comment] 2016-06-30 11:20
Thank you,  I just expected an simpler way to do it.  I'm removing the commented lines and opting for a subquery.

**Comment by marcj** [comment] 2016-06-30 12:37
@benbankes wrote already the solution. Thanks.

**Closed by marcj** 2016-06-30 12:37 UTC

**Comment by ashajjar** [comment] 2020-01-15 15:57
how do you make a sub query ?
