### ISSUE TITLE
Get a PDO instance ... error

### ISSUE THREAD

**Issue by phili67** [propelorm/Propel2#1683] opened 2020-12-12 15:10 UTC
@dereuromark i've never had this problem before, but since I upgrade from 2.0.0-alpha11 to dev-master, I get this error, each times I try to get an instance of pdo :

.... __construct() must be an instance of PDO, instance of Propel\Runtime\Connection\PdoConnection given.

So to extract the instance I use the code below

```
 // new way to manage events
        // we get the PDO for the Sabre connection from the Propel connection
        $pdo = Propel::getConnection();

        // We set the BackEnd for sabre Backends
        $calendarBackend = new CalDavPDO($pdo->getWrappedConnection());
```

CalDavPDO is a class that use sabre.io

Could you give me an advice to solve the problem ?

Thank's a lot and sorry for my poor english level.

**Comment by dereuromark** [comment] 2020-12-14 14:54
https://github.com/propelorm/Propel2/compare/2.0.0-alpha11...master#diff-65b0c78ee5e492f02556b3ef9878fa06d609655a8eded21f4cee6f6393256c3dL18
You will see that in order to be PHP8 ready, the next release will have to use an interface contract and proxy into PDO instead of just extending it.
This can have some minor BC breaking impact for e.g. your use case.
Are you able to fix up your code accordingly?

**Comment by phili67** [comment] 2020-12-21 13:45
@dereuromark How could I get the pdo interface, I always find problems with mixing sabre pdo code with propel.
I can make it work, but sometimes I've to mix sabre code with propel code and the code isn't synchronized between the two interfaces.

**Comment by dereuromark** [comment] 2021-01-12 14:03
Do you have any suggestions or a PR on what could be improved here?
We plan to do a final release soon.

**Comment by phili67** [comment] 2021-01-12 15:54
I finally find a "workaround" and it's working, but I'm not really satisfied with this solution.

**Comment by dereuromark** [comment] 2021-01-12 16:03
Do you want to elaborate a bit more?
Or shall we close this topic then?

**Comment by dereuromark** [comment] 2021-01-14 13:45
Since there is no further regression or php8 issues, I will close this now
The changelog will outline the changes regarding this BC breaking topic on release then.

**Closed by dereuromark** 2021-01-14 13:45 UTC
