### ISSUE TITLE
Failing Travis on Propel2

### ISSUE THREAD

**Issue by PhilinTv** [propelorm/Propel2#1541] opened 2020-05-06 08:30 UTC
Let's first fix Travis CI, before we start merging bugfixes.

**Comment by Incognito** [comment] 2020-06-09 13:57
Here's some details about the state of travis right now.

I re-ran tests on a commit that 2 years ago was valid and passing. (I created an empty commit and pushed to the Spryker fork). As you can see, travis infrastructure changed a lot in those 2 years and many things "broke" without any actual code change. 
![screencapture-travis-ci-org-github-propelorm-Propel2-builds-343364309-2020-06-09-14_39_35 (1)](https://user-images.githubusercontent.com/379322/84153767-9451db00-aa66-11ea-85f4-9e68e8846f88.png)
![screencapture-travis-ci-github-spryker-Propel2-builds-170515690-2020-06-09-15_55_00](https://user-images.githubusercontent.com/379322/84156307-a2552b00-aa69-11ea-9212-a68b30674bf1.png)


When looking deeper, a lot of these failures are infrastructural. For instance, the ports and permissions to connect to mysql or postgres.

I'm investigating these issues in an experimental branch to try and find fixes or options to fix them all.

- [ ] `./bin/propel test:prepare` stopped being executed in test runs, but when forced to run it appears that most tests return to passing.
- [ ] PHP5.5 is no longer supplied by travis (I propose we simply remove the item in the job matrix)
- [ ] Postgres ports change between versions of postgres that travis installs, can be fixed with a `PGPORT` envvar.
- [ ] Output log length exceeds the travis maximum and they fail the job. I propose we remove some output (or put it behind a `verbose` flag).
- [ ] sqlite install hangs, it seems to be related to file lock contention (or deadlock).
- [ ] postgres 9.2 and 9.3 fail to get installed by travis-ci correctly (`Assertion failed on job for postgresql@9.2-main.service.` while it installs it)
- [ ] mysql and mariadb simply won't connect. The Travis-ci installer complains about missing dependencies, it may be that we have to manually install some for them via apt-get.
- [ ] travis-ci simply does not attempted to install mysql in some builds.

Some of these issues could be due to travis.yml structure or parsing changes on travis-side and simply need to be modified (for example, the `matrix` key was recently renamed to `jobs`, what else changed?).

With some of these changes we can get the majority of tests running and passing again, but there are still complications that need investigation. For example, is is a run of pg9.4 with php7

![Screenshot from 2020-06-09 15-48-48](https://user-images.githubusercontent.com/379322/84155701-f0b5fa00-aa68-11ea-978a-f786ebe845df.png)
![Screenshot from 2020-06-09 15-49-06](https://user-images.githubusercontent.com/379322/84155714-f4e21780-aa68-11ea-8612-47759e2f70e6.png)

I'll also experiment if dockerization in Travis leads to more stable and predictable installs, which addresses another upcoming issue with CI: We'll need to migrate to Travis' Bionic image soon before they deprecate xenial. The images tend to have differences between them, especially with regards to ports, or required packages (for example, on older ubuntu images we could install RabbitMQ as a travis add-on instead of using apt-get).

Beyond this there are failures that appear to be software issues on the surface, but without any serious code changes I still suspect infra-churn broke them also.

**Comment by dereuromark** [comment] 2020-06-09 14:24
The dependencies could also have changed, though, right?
And similar like php74 introduced deprecations, some regressions could also come from such new dependencies being silently pulled and tested throughout the years.

**Comment by Incognito** [comment] 2020-06-10 07:49
Yes, good point. Composer changes could also have been a cause for these breaks. We'll have to dig into that too.

I also discovered travis removed the mysql service and postgres below 9.4, so I need to remove some versions and add mysql back in manually

https://docs.travis-ci.com/user/reference/bionic/#databases-and-services
![Screenshot from 2020-06-10 09-45-10](https://user-images.githubusercontent.com/379322/84240991-1ee61900-aaff-11ea-9fe3-ad09888b323e.png)
I'm going to remove 9.2 and 9.3 from the tests because the EOLd back in 2018 or earlier. https://www.postgresql.org/support/versioning/

https://docs.travis-ci.com/user/reference/xenial/#services-disabled-by-default
![Screenshot from 2020-06-10 09-47-15](https://user-images.githubusercontent.com/379322/84241157-62408780-aaff-11ea-87be-40bdaaea6d35.png)

**Comment by dereuromark** [comment] 2020-06-22 15:48
We now have master almost green ( https://travis-ci.org/github/propelorm/Propel2 )
Help of the community is greatly appreciated in terms of getting all Travis build jobs green.

**Comment by dereuromark** [comment] 2020-06-25 20:21
Propel is now green again

**Closed by dereuromark** 2020-06-25 20:21 UTC
