### ISSUE TITLE
`deleted` column conflicts with propels own `deleted` attribute

### ISSUE THREAD

**Issue by mpscholten** [propelorm/Propel2#771] opened 2014-10-07 12:14 UTC
Let's say we have a table `user` with the following column:
`<column name="deleted" type="CHAR" sqlType="enum(....)"/>`

The generated object model will now look like this:
```php
    /**
     * The value for the deleted field.
     * @var        string
     */
    protected $deleted;
```

But propel already generated a property with the same name for internal use:
```php
    /**
     * attribute to determine whether this object has been deleted.
     * @var boolean
     */
    protected $deleted = false;
```

Which results in `Fatal error: Cannot redeclare User::$deleted in /Base/User.php on line xxx`

----
Propel should warn us about this conflict; or even better should not name internal properties with general names (maybe add a prefix?).

**Comment by triskil** [comment] 2015-01-13 21:03
Has this been resolved? I'm having the same issue with propel confusing the internal deleted property with my table's deleted column.

**Comment by mpscholten** [comment] 2015-01-13 21:16
Not really, but I think you can use `<column name="removed" sqlName="deleted"/>` as a workaround.

**Comment by triskil** [comment] 2015-01-13 21:48
That stopped the conflict but when I try to query. I get an SQL error because propel thinks the column name is 'removed' instead of 'deleted'. 

Here is the line in the schema.xml

<column name="removed" sqlName="deleted" type="BOOLEAN" size="1" defaultValue="false"/>

**Comment by marcj** [comment] 2015-01-13 21:52
You should rather use `<column name="deleted" phpName="Removed" />`

**Comment by triskil** [comment] 2015-01-13 21:59
propel still tries to create two conflicting properties in the base class if I use 

`<column name="removed" phpName="deleted" type="BOOLEAN" size="1" defaultValue="false"/>`

The base class creates
```
/**
     * attribute to determine whether this object has been deleted.
     * @var boolean
     */
    protected $deleted = false;
```

But also adds this column property not using the phpName

```
/**
     * The value for the deleted field.
     * Note: this column has a database default value of: false
     * @var        boolean
     */
    protected $deleted;
```

Also in the accessor for the column it references the deleted property not 'removed'

```
/**
     * Get the [deleted] column value.
     *
     * @return boolean
     */
    public function getRemoved()
    {
        return $this->deleted;
    }
```

Is this a bug?

**Comment by marcj** [comment] 2015-01-13 22:06
I guess you have rather mixed now something. A `phpName` of `"deleted"` does definitely not create getter methods like `getRemoved`. However, it's wrong what you have tried. I gave you a other xml snipped than you're using.

**Comment by triskil** [comment] 2015-01-14 16:20
I've copy pasted the line you gave me and I get the same result. Changing the phpName doesn't seem to stop the error. :( 

`<column name="deleted" phpName="Removed" />`

I'm on version ~2.0@dev installed via composer. I can try making a simple version of the schema.xml to reproduce the issue.

**Comment by triskil** [comment] 2015-01-14 16:25
Actually I noticed there is also an index for this table that is in the schema.xml named deleted. Would this also need phpName to be changed to avoid conflicting?

```
<index name="not_deleted">
      <index-column name="deleted" size="1"/>
    </index>
```

**Comment by mpscholten** [comment] 2015-02-04 15:19
Maybe we could change the ObjectBuilder to name the class properties after the `phpName` instead of naming them after the `name`. Then one could use `<column name="deleted" phpName="removed"/>` as a workaround.

Plan B is waiting for the data-mapper branch. But I don't know how far @marcj has progressed on this.

**Comment by agwidarsito** [comment] 2015-02-07 01:28
Wait...there's a data mapper branch? Where can I find out more @marcj ?

**Comment by staabm** [comment] 2015-02-07 07:59
@agwidarsito see WIP in https://github.com/propelorm/Propel2/pull/795

**Comment by justechn** [comment] 2015-11-29 23:30
I am running into this problem with a project I am working on. How can I use propel 2 and have a tabled with a deleted column?

**Comment by mpscholten** [comment] 2015-11-30 08:55
There's no way to solve this until #795 is finished. Take a look at doctrine in case you need a solution right now :)

**Comment by agwidarsito** [comment] 2015-11-30 10:26
@justechn This is a frustrating issue :/

**Comment by sitilge** [comment] 2016-10-05 11:16
End of 2016, still having this issue.

**Comment by marcj** [comment] 2016-10-05 11:28
Is fixed in `data-mapper` branch.

**Closed by marcj** 2016-10-05 11:28 UTC
Labels: Feature

**Comment by justechn** [comment] 2016-10-05 13:09
@marcj Any idea when this branch will be ready for production?
