### ISSUE TITLE
php function current doesn't work with ObjectCollection

### ISSUE THREAD

**Issue by sebastian301082-KAM** [propelorm/Propel2#946] opened 2015-06-12 09:49 UTC
I saw in a project following code and I'm not sure if there is a problem in propel or if this shouldn't work at all.

```
$books = $author->getBooks();
$book = current($books);
var_dump($book);
```

or

```
$collection = new ObjectCollection(
    [
        new Book(),
        new Book(),
    ]
);
var_dump(current($collection));
```

In both cases var_dump printend following code:
```
array(2) {
  '000000002d6b9b740000000021933b71' =>
  int(0)
  '000000002d6b9b780000000021933b71' =>
  int(1)
}
```

But expected was a single instance of Book.

Please let me know if this is an issue in propel or if this is an expected behaviour.

**Comment by marcj** [comment] 2015-06-12 10:00
I get different results: http://sandbox.propelorm.org/b2b9db1

**Comment by sebastian301082-KAM** [comment] 2015-06-12 10:11
Strange that you got a different result. You get a string returned. Still I expected to get an instance of Book returned.

This is not working either: http://sandbox.propelorm.org/47160bd

**Comment by sebastian301082** [comment] 2015-06-19 07:59
+1

**Comment by mreichenbach-igniti** [comment] 2015-06-19 08:03
+1

**Comment by SCIF** [comment] 2015-07-02 16:37
@sebastian301082 
```php
class Collection implements \ArrayAccess, \IteratorAggregate, \Countable, \Serializable
```

It's not a bug. current/next/key() are methods of [Iterator](http://php.net/manual/en/class.iterator.php) interface which is not implemented by Collection. But you can use IteratorAggregate interface and work with Iterator via `getIterator()` — http://sandbox.propelorm.org/d7dbc1a Also, you are trying call method from Author on Book object.

**Comment by SCIF** [comment] 2015-07-02 16:42
@marcj , why `Collection` not implemented `Iterator`?

**Comment by marcj** [comment] 2015-07-02 17:02
Because we use already `IteratorAggregate`

**Comment by SCIF** [comment] 2015-07-02 17:05
It's not very intuitive and current issue which 20 days was not solved is prove my supposition. :D

**Comment by SCIF** [comment] 2015-07-02 17:08
`CollectionIterator` duplicate some methods of `Collection` and uses only in `getIterator()` method, isn't it?

**Comment by marcj** [comment] 2015-07-02 17:23
Not responding 20 days has nothing todo with intuitive, it just means everyone is busy. `Collection` has just not implemented the `Iterator` or `SeekableIterator` interface, that's why array access functions like `current`, `end` et cetera don't work. So if someone is going to implement it without memory leaks this will be surely merged.

**Closed by marcj** 2015-07-02 17:23 UTC

**Comment by sebastian301082** [comment] 2015-07-30 06:19
If it is not possible to use functions like current in correct way. Would it be more intuitive, if there will be an Exception or Error if someone  try to use it. Currently returning random information is quite smelly and leads to wrong assumptions.

**Comment by SCIF** [comment] 2015-07-30 06:27
@sebastian301082-KAM , what you are talking about? Did you read my answer?? I explained everything and create correct example in sandbox. If you can't understand that simple things, it's your problem, not Propel issues.

**Comment by sebastian301082** [comment] 2015-07-30 06:55
@SCIF. First and most important: Don't be that rud!!!! I'm just trying to help!
I got your example and I use it already this way.

I'm just suggesting that if someone still uses it, the wrong way, like in original example. It would be good to throw a proper error or exception explaining that this is wrong way to go. But returning "ANY" information is not working in my opinion and leads to wrong assumptions.

Remember I just try to help and make propel2 even better! No offence!
