### ISSUE TITLE
propel init doubles namespaces for generated model classes

### ISSUE THREAD

**Issue by hsegnitz** [propelorm/Propel2#1260] opened 2016-08-30 07:46 UTC
When I "propel init" a project with an existing Mysql database and let propel auto-generate the orm classes, it doubles the namespace.

If I supply "Namespace1\Subnamespace" it will make it "Namespace1\Subnamespace\Namespace1\Subnamespace". This is reflected everywhere in the generated files, even in the folder structure.

Screenshot should show what I've entered and what came out of it.

I'm on master, commit: 884856fc514e2a6afdabc942ecc9c5bc5ee83ce9

![propel-namespace-duplication](https://cloud.githubusercontent.com/assets/2615958/18080618/927ae1ce-6e96-11e6-8d43-c9d24a7be60f.png)

**Comment by hsegnitz** [comment] 2016-08-30 13:31
Found the reason:

the reverse-engineered schema.xml has the namespace twice -- for the whole database and then again for the tables.


`.....  <database name="default" defaultIdMethod="native" namespace="FastBill\TraceAnalyzer\Models" defaultPhpNamingMethod="underscore">
  <table name="files" idMethod="native" phpName="Files" namespace="FastBill\TraceAnalyzer\Models"> .....`


If I remove the database's namespace by setting it to   namespace=""  the generated code looks okay.

**Comment by marcj** [comment] 2016-08-30 16:52
Good catch! Then I think the reverse class has some issues.

**Comment by narkoticro** [comment] 2016-09-13 08:24
Same issue when using with Postgres.

**Comment by gustavonecore** [comment] 2017-12-17 03:00
Any idea if we can avoid that global namespace for the database at command level?
I don't see any option to do that...
I want to maintain those commands in the same bash script as a shorcut..

```
./propel database:reverse --config-dir=config/local/ --namespace="Leftaro\App\Model" --output-dir=etc;

...remove database namespace here via sed

./propel build --schema-dir=etc --output-dir=src/App/Model --disable-namespace-auto-package --config-dir=config/local/;
```

**Comment by benbankes** [comment] 2018-02-06 09:40
Using `--namespace="\Leftaro\App\Model"` is a workaround for this bug.  This issue is a duplicate of #1233   There are two PRs for that issue which are awaiting review.

**Comment by gustavonecore** [comment] 2018-02-06 13:09
Thanks for the insight @benbankes.
I was able to fix it with a custom php script but I'll wait the fix 
Cheers

**Comment by dereuromark** [comment] 2020-07-01 12:55
Closing in favor of other ticket.

**Closed** 2020-07-01 12:55 UTC
Labels: Bug
