### ISSUE TITLE
Invoking database:reverse incorrectly duplicates namespace in schema.xml table element

### ISSUE THREAD

**Issue by benbankes** [propelorm/Propel2#1233] opened 2016-07-04 17:43 UTC
The command `propel database:reverse` places the value from the `--namespace` option in the namespace attribute of both the `database` and `table` xml elements, causing the table's namespace.  When a namespace of `Foo` is used for the `--namespace` option of the command, the following xml results:

```
<database name="my_db" namespace="Foo">
  <table name="user" namespace="Foo">
  </table>
</database>
```

Per the namespace inheritance rules at http://propelorm.org/documentation/cookbook/namespaces.html, this would create a class `User` with the namespace `Foo\Foo`, which is not intended.

**Comment by dereuromark** [comment] 2020-07-01 12:56
Which PR would be preferred at this time?
// cc @Incognito

**Comment by benbankes** [comment] 2020-07-01 16:22
I would prefer #1235, since it would also fixes lots of other tests where the namespace of the schema.xml in those tests do not follow the same rules as specified in the documentation. However, this fix does limit the affected code to only the bug specified in #1233, which others may think is preferable.

**Comment by Incognito** [comment] 2020-07-13 09:03
#1241 is rebasable, passes CI, and appears to remove the concept of namespaces on tables.

#1235 is also rebasable and passes CI (except for 1 issue in `Propel/Generator/Schema/Dumper/XmlDumper.php` with phpstan validation). It appears to change namespaces on tables as intended.

What I'm not yet 100% up-to-date on: should tables have namespaces or not? What's the point?

**Comment by benbankes** [comment] 2020-07-14 19:04
@Incognito I am unsure what you are referencing when you say the phrase "namespaces on tables".  It is useful to have namespaces on the PHP classes which are automatically generated.  I don't see any other utility for the "namespace" keyword in the `schema.xml` file.

**Comment by Incognito** [comment] 2020-07-15 09:29
:point_up_2: I agree with your perspective on what is useful.

Do you see #1235 as more useful than #1241? I was expecting #1241 to be the better choice at first glance.

**Comment by benbankes** [comment] 2020-07-17 17:39
I do see #1235 as more useful, but there is always the possibility that I may be missing some information.

**Comment by dereuromark** [comment] 2020-07-17 18:24
1241 seems to have less BC impact than 1235 from first glance.

**Comment by sudofox** [comment] 2021-03-18 18:57
Okay, so this is an actual bug? I've been trying to work out why the namespace I entered gets duplicated

**Comment by mringler** [comment] 2021-03-18 19:08
@sudofox lol I remember how that drove me crazy. Didn't know this was fixed four times, and no one ever merged it. Could have saved me an hour, and apparently you too.
Workaround that solved the issue for me was to start the namespace with a backslash, i.e. `\MyProject\Model` instead of `MyProject\Model`. Hope that helps.

**Closed** 2021-05-19 21:12 UTC
Labels: Bug
