### ISSUE TITLE
Add synfony 5 compatibility

### ISSUE THREAD

**Issue by Snake231088** [propelorm/Propel2#1534] opened 2020-03-06 11:47 UTC
Add synfony 5 compatibility

**Comment by acabutto** [comment] 2020-03-10 10:37
+1

**Comment by spartan** [comment] 2020-03-14 16:01
+1

**Comment by dereuromark** [comment] 2020-05-05 18:06
PR open: https://github.com/propelorm/Propel2/pull/1536
Is it confirmed by someone that it fully works?

**Comment by dereuromark** [comment] 2020-06-23 10:06
We now have master almost green ( https://travis-ci.org/github/propelorm/Propel2 )
Help of the community is greatly appreciated in terms of getting all Travis build jobs green.

As for this issue, we opened a follow up ticket now and it turns out this lib is not really fully compatible with Symfony 5 yet. Some bugs need fixing.
If anyone could open a PR here that would be greatly appreciated.

**Comment by dereuromark** [comment] 2020-06-30 14:10
Closing in favor of main ticket https://github.com/propelorm/Propel2/issues/1578

**Closed by dereuromark** 2020-06-30 14:10 UTC
